-- Дополнительные необязательные поля сотрудника (User)
ALTER TABLE "User" ADD COLUMN IF NOT EXISTS "birthDate" TIMESTAMP(3);
ALTER TABLE "User" ADD COLUMN IF NOT EXISTS "workStartDate" TIMESTAMP(3);
ALTER TABLE "User" ADD COLUMN IF NOT EXISTS "emailWork" TEXT;
ALTER TABLE "User" ADD COLUMN IF NOT EXISTS "emailGoogle" TEXT;
ALTER TABLE "User" ADD COLUMN IF NOT EXISTS "phonePersonal" TEXT;
ALTER TABLE "User" ADD COLUMN IF NOT EXISTS "phoneWork" TEXT;
ALTER TABLE "User" ADD COLUMN IF NOT EXISTS "telegramPersonal" TEXT;
ALTER TABLE "User" ADD COLUMN IF NOT EXISTS "telegramWork" TEXT;
ALTER TABLE "User" ADD COLUMN IF NOT EXISTS "hasSpouse" BOOLEAN;
ALTER TABLE "User" ADD COLUMN IF NOT EXISTS "hasChildren" BOOLEAN;
ALTER TABLE "User" ADD COLUMN IF NOT EXISTS "childrenCount" INTEGER;
ALTER TABLE "User" ADD COLUMN IF NOT EXISTS "childrenBirthDates" TEXT;
